import puppeteer from "puppeteer";
import fs from "fs";
import path from "path";

async function run() {
  console.log("[Cookies Setup] Launching headless browser...");
  let browser;
  try {
    browser = await puppeteer.launch({
      headless: "new",
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--single-process"
      ]
    });

    const page = await browser.newPage();
    
    // Set a normal user agent to look like a real browser
    await page.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36");

    console.log("[Cookies Setup] Navigating to YouTube Home...");
    await page.goto("https://www.youtube.com", { waitUntil: "networkidle2", timeout: 30000 });
    await new Promise(resolve => setTimeout(resolve, 2000));

    console.log("[Cookies Setup] Navigating to a YouTube video page to trigger player/visitor validation...");
    await page.goto("https://www.youtube.com/watch?v=JV_et_kRpLU", { waitUntil: "networkidle2", timeout: 30000 });
    await new Promise(resolve => setTimeout(resolve, 4000));

    console.log("[Cookies Setup] Extracting cookies...");
    const cookies = await page.cookies();
    console.log(`[Cookies Setup] Found ${cookies.length} browser cookies.`);

    // Convert to Netscape cookie format
    let netscapeContent = "# Netscape HTTP Cookie File\n";
    netscapeContent += "# This file was generated by Puppeteer headless browser\n\n";

    for (const cookie of cookies) {
      const domain = cookie.domain;
      const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
      const path = cookie.path || "/";
      const secure = cookie.secure ? "TRUE" : "FALSE";
      
      // Far-future timestamp for session cookies (10 years from now)
      const expiration = cookie.expires && cookie.expires > 0 
        ? Math.floor(cookie.expires) 
        : Math.floor(Date.now() / 1000) + (10 * 365 * 24 * 60 * 60);
      
      const name = cookie.name;
      const value = cookie.value;

      netscapeContent += `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expiration}\t${name}\t${value}\n`;
    }

    const cookiesPath = path.join(process.cwd(), "cookies.txt");
    fs.writeFileSync(cookiesPath, netscapeContent, "utf8");
    console.log(`[Cookies Setup] Cookies file successfully written to ${cookiesPath}`);

  } catch (err) {
    console.error("[Cookies Setup] Failed to extract cookies:", err);
  } finally {
    if (browser) {
      await browser.close();
    }
  }
}

run();
